default_install_hook_types:
  - pre-commit
  - post-checkout
  - post-merge
  - post-rewrite

repos:
  - repo: https://github.com/astral-sh/uv-pre-commit
    # uv version.
    rev: 0.9.3
    hooks:
      - id: uv-sync

  - repo: https://github.com/astral-sh/uv-pre-commit
    # uv version.
    rev: 0.9.3
    hooks:
      # Update the uv lockfile
      - id: uv-lock

  - repo: https://github.com/astral-sh/ruff-pre-commit
    # Ruff version.
    rev: v0.14.1
    hooks:
      # Run the linter.
      - id: ruff-check
        args: [ --fix ]
      # Run the formatter.
      - id: ruff-format

  - repo: https://github.com/shyndman/ai-deroot-pre-commit
    rev: v0.0.9
    hooks:
      - id: setup-managed-symlinks
        args: [--hidden-dir=.ai, '--files=CLAUDE.md,AGENTS.md,.claude', --migrate=move]
      - id: check-managed-symlinks
        args: [--hidden-dir=.ai, '--files=CLAUDE.md,AGENTS.md,.claude']
      - id: update-gitignore-for-symlinks
        args: [--hidden-dir=.ai, '--files=CLAUDE.md,AGENTS.md,.claude']

#  - repo: local
#    hooks:
#      - id: ty
#        name: ty check
#        entry: uv run ty check
#        language: python
